SELECT * FROM STUDENT WHERE DATEADD('YEAR', 20, BIRTHDAY) <= current_date;

SELECT * FROM PAYMENT WHERE AMOUNT >= 500;

SELECT * FROM STUDENT  WHERE STUDENT.NAME LIKE '%Mike%' or GROUPNUMBER in (4,5,6);

SELECT * FROM PAYMENT WHERE PAYMENT_DATE >= DATE_TRUNC('MONTH', NOW() - INTERVAL '8' MONTH);

SELECT * FROM STUDENT WHERE NAME LIKE 'A%';


SELECT * FROM STUDENT WHERE STUDENT.NAME LIKE '%Roxi%' AND STUDENT.GROUPNUMBER=4
                         OR STUDENT.NAME LIKE '%Tallie%' AND STUDENT.GROUPNUMBER=9;


SELECT * FROM STUDENT WHERE STUDENT.GROUPNUMBER = 10 and DATEADD('YEAR', 20, BIRTHDAY) >= CURRENT_DATE;
